### ISSUE TITLE
Sending invites: Please comment your username here to get an invite.

### ISSUE THREAD

**Issue by satwikkansal** [wtfpython-web/wtfpython-web#11]
- To get assigned to an issue, you'll first have to invited by us to the organization!
- You'll then receive an email.
- Once the invite if accepted, only then we'd be able to assign you to the issue.

**Update:** To get an invite, just visit [this](https://wtfpython-web-invite.herokuapp.com/) link and enter your username there. 

**If the above ^^ method fails for you, let us know by commenting here, otherwise ignore the rest of the message!**

Right now, we have manual process so you can comment here and I'll add member in batches. **People already invited, please ignore!**

A more cleaner approach is https://github.com/wtfpython-web/wtfpython-web/issues/4 which we're waiting for some participant to solve (you can solve it too, btw), but until then, let's use this approach

**Note:** A thumbs-up (:+1:) react to your comment by me or any of the @wtfpython-web/mentors means you've been sent an invite, so just check your email to accept it.

**Comment by pritamnegi** [comment]
pritamnegi

**Comment by Pradhvan** [comment]
Github Handel: Pradhvan 

Profile link: ``` https://github.com/Pradhvan```

**Comment by Logan1x** [comment]
@logan1x

**Comment by iriyagupta** [comment]
@riya2908

**Comment by Eunoia1729** [comment]
Eunoia1729

**Comment by shreyateeza** [comment]
My github handle: @shreyateeza

**Comment by devesh-verma** [comment]
Github Handel: devshiva619

Profile link: https://github.com/devshiva619

**Comment by parulagg27** [comment]
@parulagg27

**Comment by satwikkansal** [comment]
Would anyone like to check https://wtfpython-web-invite.herokuapp.com/ if it's working (it should send you an email)

@parulagg27 would you like to try ^^

**Comment by parulagg27** [comment]
Yes, it's working! @satwikkansal

**Comment by satwikkansal** [comment]
Awesome :tada:

**Comment by realslimshanky** [comment]
@satwikkansal I suggest we close this issue and post the invite link on README.md and wiki as well.
This would clear the space on issues tab just for the active issues.

**Comment by satwikkansal** [comment]
@realslimshanky Yeah, that's a nice idea.

Actually, the  https://wtfpython-web-invite.herokuapp.com/  link is still buggy and fails 50% of the time, let's keep it open for a couple of days more, and then if it works smoothly we can close this.

**Comment by realslimshanky** [comment]
@satwikkansal sure. Until we fix that. It would be better if we can upload the code for invite web app to a separate repository here in this org.

**Comment by satwikkansal** [comment]
Alright, I've forked it under our org, https://github.com/wtfpython-web/automated-github-organization-invites

Now we can customize it if we like! And yeah, this link seems to be working fine, so closing this issue.

If anyone has troubles with the invites feel free to re-open it or create a separate issue :)

**Comment by sourabhpruthi10** [comment]
@sourabh1031
