### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by satwikkansal** [wtfpython-web/wtfpython-web#17]
This should be a follow up of https://github.com/wtfpython-web/wtfpython-web/issues/3 as a checklist to ensure whether the contributors has performed all the necessary actions (run the tests, followed PEP 8, structured commit message, etc) before creating a PR.

See https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/ for how to create one.

**Comment by devesh-verma** [comment]
hey I would like to work on this.

**Comment by Pallavi024** [comment]
I would like to work on this

**Comment by satwikkansal** [comment]
Assigned @Pallavi024 since @devshiva619 is already working on another issue (let's do it one at a time guys, so that everyone get something to work on, and we can maximize our efficiency)
