### ISSUE TITLE
Setting up a slackbot

### ISSUE THREAD

**Issue by satwikkansal** [wtfpython-web/wtfpython-web#4]
Idea by @jainaman224 

A simple chatbot can be create with various commands like

- `invite`: Invite people to the repository (It's a tedious and manual process rn)
- `assign`: To get assigned to a particular issue
- `create`: To create a new issue
- similar stuff

and some highly useful commands like
- `send_memes`: To deliver memes

**Comment by satwikkansal** [comment]
You can fork https://github.com/coala/corobo and make appropriate changes to get it working!

**Comment by Dhiraj240** [comment]
I would like to take up this issue next.

**Comment by shreyateeza** [comment]
@Dhiraj240 Are you still working on this issue? Please reply!
I too would like to work on this issue! @satwikkansal

**Comment by Dhiraj240** [comment]
@shreyateeza Yes,its a long task so please take up any other task as i am building the bot from scratch.I am  updating everything to @satwikkansal  and it will be done in few days.Hence please look at other issues.

**Comment by satwikkansal** [comment]
@shreyateeza you could also work on it after we have some code merged from @Dhiraj240's end. I've assigned you to https://github.com/wtfpython-web/wtfpython-web/issues/7 until then :D
