### ISSUE TITLE
Github slack integration

### ISSUE THREAD

**Issue by satwikkansal** [wtfpython-web/wtfpython-web#8]
Since we're using slack as our communication channel, it'd be nice to have https://github.com/integrations/slack implemented.

/difficulty/pro

**Comment by satwikkansal** [comment]
This might also be used to solve https://github.com/wtfpython-web/wtfypython-web/issues/4

**Comment by Dhiraj240** [comment]
@satwikkansal  can i work on this issue ?

**Comment by satwikkansal** [comment]
Assigned. Do let us know till when you'll be able to finish this :)

**Comment by Dhiraj240** [comment]
I guess,by tonight it will be done.

**Comment by Dhiraj240** [comment]
Testing the github slack integration

**Comment by Dhiraj240** [comment]
I have added the github app too the channel and also sent a request to install slack for the respective repository.In order to test it,installation is necessary by your side.

**Comment by jainaman224** [comment]
@satwikkansal Please do the needful.

**Comment by Dhiraj240** [comment]
@jainaman224 It is done please close the issue.

**Comment by satwikkansal** [comment]
Yeah, closing it.

@Dhiraj240 your blog post is still due btw :) Make sure to share it once you're done with it!

**Comment by Dhiraj240** [comment]
I just need 1 day and after that i will be on.
